service: my-app
image: mujdat/build-info

servers:
  web:
    - "<%= ENV['DEPLOY_HOST'] %>"

proxy:
  ssl: true
  host: <%= ENV['BUILD_INFO_HOST'] %>
  app_port: 3131
  healthcheck:
    path: /

registry:
  username: mujdatkorkmaz
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
